name: Deploy Laravel Project
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@master
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Clear cache
        run: php artisan config:cache
      - name: Optimize
        run: php artisan optimize:clear --no-ansi --no-interaction
      - name: nodejs
        run: npm ci --include=dev
      - name: run build
        run: sudo npm run build
      # - name: Run migrations
      #   run: php artisan migrate --force --no-ansi --no-interaction
      # - name: Generate storage link
      #   run: php artisan storage:link
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: /